/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chapter09;

/**
 *
 * @author MO
 */
//An exception can be generated by one  method and caught by another
class ExcTest {

    //generate exception
    static void genException() {
        int nums[] = new int[4];
        System.out.println("Before generated");

        //generate index exception
        nums[7] = 10;
        System.out.println("not shown");
    }
}

public class ExcDemo2 {

    public static void main(String args[]) {

        try {
            ExcTest.genException();
        } catch (ArrayIndexOutOfBoundsException exc) {
            // catch the exception  
            System.out.println("Index out-of-bounds!");
        }
        System.out.println("After catch statement.");
    }
}
