/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chapter16;

/**
 *
 * @author MO
 */
// Demonstrate check boxes. 
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class CDemo implements ItemListener {

    JLabel jlabSelected;
    JLabel jlabChanged;
    JCheckBox jcbAlpha;
    JCheckBox jcbBeta;
    JCheckBox jcbGamma;

    CDemo() {

        //create fram container
        JFrame jframe = new JFrame("shows check boxes");

        //flowlayout for the layer manager
        jframe.setLayout(new FlowLayout());

        //set initial values
        jframe.setSize(280, 120);

        //terminating programm
        jframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Create empty labels. 
        jlabSelected = new JLabel("");
        jlabChanged = new JLabel("");

        // Make check boxes. 
        jcbAlpha = new JCheckBox("Alpha");
        jcbBeta = new JCheckBox("Beta");
        jcbGamma = new JCheckBox("Gamma");

        // Events generated by the check boxes 
        // are handled in common by the itemStateChanged() 
        // method implemented by CBDemo. 
        jcbAlpha.addItemListener(this);
        jcbBeta.addItemListener(this);
        jcbGamma.addItemListener(this);

        // Add checkboxes and labels to the content pane.  
        jframe.add(jcbAlpha);
        jframe.add(jcbBeta);
        jframe.add(jcbGamma);
        jframe.add(jlabChanged);
        jframe.add(jlabSelected);

        // Display the frame.  
        jframe.setVisible(true);
    }

    // This is the handler for the check boxes.   
    public void itemStateChanged(ItemEvent ie) {
        String str = "";

        // Obtain a reference to the check box that 
        // caused the event. 
        JCheckBox cb = (JCheckBox) ie.getItem();

        // Report what check box changed. 
        if (cb.isSelected()) {
            jlabChanged.setText(cb.getText() + " was just selected.");
        } else {
            jlabChanged.setText(cb.getText() + " was just cleared.");
        }

        // Report all selected boxes. 
        if (jcbAlpha.isSelected()) {
            str += "Alpha ";
        }
        if (jcbBeta.isSelected()) {
            str += "Beta ";
        }
        if (jcbGamma.isSelected()) {
            str += "Gamma";
        }

        jlabSelected.setText("Selected check boxes: " + str);
    }

    public static void main(String args[]) {
        // Create the frame on the event dispatching thread.  
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new CDemo();
            }
        });
    }
}